2025-01-04 01:34:00,308 ERROR scheduler Exception in Enqueue Events for Site mysite
Traceback (most recent call last):
  File "/home/test/night-bench/apps/frappe/frappe/utils/scheduler.py", line 105, in enqueue_events_for_site
  File "/home/test/night-bench/apps/frappe/frappe/utils/scheduler.py", line 149, in is_scheduler_inactive
  File "/home/test/night-bench/apps/frappe/frappe/utils/scheduler.py", line 162, in is_scheduler_disabled
    else:
  File "/home/test/night-bench/apps/frappe/frappe/database/database.py", line 872, in get_single_value
    run=True,
         ^^^^^
  File "/home/test/night-bench/apps/frappe/frappe/__init__.py", line 1313, in get_meta
  File "/home/test/night-bench/apps/frappe/frappe/model/meta.py", line 81, in get_meta
    for d in txt.get("fields", []):
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/functools.py", line 946, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/night-bench/apps/frappe/frappe/model/meta.py", line 138, in _
    self.apply_property_setters()
    ^^^^^^^^^^^^^^
  File "/home/test/night-bench/apps/frappe/frappe/model/meta.py", line 176, in process
    def get_phone_fields(self):
  File "/home/test/night-bench/apps/frappe/frappe/model/meta.py", line 583, in set_custom_permissions
    return permitted_fieldnames
                   ^^^^^^^^^^^^
  File "/home/test/night-bench/apps/frappe/frappe/__init__.py", line 2018, in get_all
    def get_value(*args, **kwargs):
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/night-bench/apps/frappe/frappe/__init__.py", line 1993, in get_list
    def get_all(doctype, *args, **kwargs):
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/night-bench/apps/frappe/frappe/model/db_query.py", line 203, in execute
  File "/home/test/night-bench/apps/frappe/frappe/model/db_query.py", line 218, in build_and_run
    args.fields = "distinct " + args.fields
          ^^^^^^^^^^^^^^^^^^^
  File "/home/test/night-bench/apps/frappe/frappe/model/db_query.py", line 258, in prepare_args
    args.tables = self.tables[0]
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/night-bench/apps/frappe/frappe/model/db_query.py", line 566, in build_conditions
    if isinstance(each, str):
  File "/home/test/night-bench/apps/frappe/frappe/model/db_query.py", line 581, in build_filter_conditions
    self.build_filter_conditions(self.filters, self.conditions)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/night-bench/apps/frappe/frappe/model/db_query.py", line 692, in prepare_filter_condition
    continue
             
  File "/home/test/night-bench/apps/frappe/frappe/boot.py", line 378, in get_additional_filters_from_hooks
    filter_config.update(frappe.get_attr(hook)())
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/night-bench/apps/frappe/frappe/__init__.py", line 1711, in get_attr
    if not local.flags.in_uninstall and not local.flags.in_install and app_name not in get_installed_apps():
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/night-bench/apps/frappe/frappe/__init__.py", line 1429, in get_module
    )
      
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'
